### ISSUE TITLE
Not compatible with latest Telegram bot Python library

### ISSUE THREAD

**Issue by thonixx** [Jiaconda/SBB_Telegram_bot#1]
It seems that something has changed in the Python library for Telegram bots. So would it be possible that you can look into this? I tried to fix by myself but as an unexperienced Python user I did not come far.

**Comment by thonixx** [comment]
The error message I stumbled upon is:
`Traceback (most recent call last):
  File "sbb_bot.py", line 3, in <module>
    from telegram import Updater, ParseMode
ImportError: cannot import name Updater`

and with changing the telegram import to telegram.ext it gives the following error:
`Traceback (most recent call last):
  File "sbb_bot.py", line 3, in <module>
    from telegram.ext import Updater, ParseMode
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 29, in <module>
    from telegram import (TelegramError, NullHandler)
ImportError: cannot import name TelegramError`

**Comment by BafS** [comment]
The issue should be fixed, thanks for the feedback.

**Comment by thonixx** [comment]
Issue seems to persist with latest version of Python Telegram library as follows:
`Traceback (most recent call last):
  File "sbb_bot.py", line 4, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 29, in <module>
    from telegram import (TelegramError, NullHandler)
ImportError: cannot import name TelegramError`

Is it something I did wrong? I installed the Telegram library via `pip install python-telegram-bot`.

**Comment by thonixx** [comment]
Ok I know why. I have removed the Python library "telegram" which was also installed. Now it works fine. Sorry for the trouble. I hope you don't mind when I fork and improve it.

**Comment by BafS** [comment]
Okay nice. Of course, that would be really welcome, thanks to you.
